// Embeds what Help shows into src/generated/help-assets.ts, so the single
// HTML file needs no other file and no network at runtime:
//
//   * LICENSE (the full license text, for Help → License);
//   * docs/img/manual/*.webp (the screenshots of Help → User Manual, taken
//     from the application by scripts/manual-screenshots.mjs), as data: URLs
//     with their pixel sizes.
//
//   node scripts/gen-help.mjs           write the module
//   node scripts/gen-help.mjs --check   verify that the committed module is current
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const imgDir = join(root, 'docs', 'img', 'manual');

/** Width and height of a WebP image (lossy VP8, lossless VP8L or extended VP8X). */
export function webpSize(buf) {
  if (buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WEBP') throw new Error('not a WebP image');
  const chunk = buf.toString('ascii', 12, 16);
  if (chunk === 'VP8 ') return { width: buf.readUInt16LE(26) & 0x3fff, height: buf.readUInt16LE(28) & 0x3fff };
  if (chunk === 'VP8L') {
    const b = buf.readUInt32LE(21);
    return { width: (b & 0x3fff) + 1, height: ((b >> 14) & 0x3fff) + 1 };
  }
  if (chunk === 'VP8X') return { width: buf.readUIntLE(24, 3) + 1, height: buf.readUIntLE(27, 3) + 1 };
  throw new Error('unknown WebP chunk ' + chunk);
}

const license = readFileSync(join(root, 'LICENSE'), 'utf8').replace(/\r\n/g, '\n');
const images = {};
for (const f of existsSync(imgDir) ? readdirSync(imgDir).filter((x) => /\.webp$/.test(x)).sort() : []) {
  const buf = readFileSync(join(imgDir, f));
  images[f.replace(/\.webp$/, '')] = { src: 'data:image/webp;base64,' + buf.toString('base64'), ...webpSize(buf) };
}
const out =
  '// GENERATED by scripts/gen-help.mjs from LICENSE and docs/img/manual/*.webp — do not edit.\n' +
  '\n/** The full text of the LICENSE file (Help → License). */\n' +
  'export const LICENSE_TEXT: string = ' + JSON.stringify(license) + ';\n' +
  '\n/** The screenshots of Help → User Manual, by name: data: URLs and their sizes in pixels. */\n' +
  'export const MANUAL_IMAGES: { [name: string]: { src: string; width: number; height: number } } = ' + JSON.stringify(images, null, 2) + ';\n';
const target = join(root, 'src', 'generated', 'help-assets.ts');
if (process.argv.includes('--check')) {
  let cur = '';
  try {
    cur = readFileSync(target, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    /* missing */
  }
  if (cur !== out) {
    console.error('src/generated/help-assets.ts is out of date: run "npm run build" and commit the result');
    process.exit(1);
  }
  console.log(`src/generated/help-assets.ts is up to date (LICENSE, ${Object.keys(images).length} manual images)`);
} else {
  mkdirSync(join(root, 'src', 'generated'), { recursive: true });
  writeFileSync(target, out);
  const kib = Object.values(images).reduce((n, i) => n + i.src.length, 0) / 1024;
  console.log(`embedded LICENSE and ${Object.keys(images).length} manual images (${kib.toFixed(1)} KiB as data: URLs)`);
}
